; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.orgp/age/projectconf.html

[platformio]
extra_configs =
	      secrets.ini
;	      secrets-usb.ini
	      secrets-wifi.ini
; raised bed 2 0x0149 (10.71.71.135) "1"
;	      board4.ini
; backyard 0x5d6e (10.71.71.138) "2"
;	      board5.ini
; blueberries 0x5da1 ("3") (10.71.71.136)
;	      board6.ini
; dev "4" 0x66dd 10.71.71.137
;	      board7.ini
; dev "5" 0x5d7d
;	      board8.ini
; v6.2 boards "9" "1c" 10.71.71.141
;	      board62a.ini
; xxx board id 5d9a, "10", 10.71.71.142 -- bed 1 "Raised bed 1"
;	      board62b.ini
; board id 5d0b, "11", 10.71.71.143 -- bed 3 "Raised bed 3"
;	      board62c.ini
; board id 5db6, "12", 10.71.71.144 -- new raised-bed-1
;	      board62d.ini
; board id 5dc4, "13", 10.71.71.145
;	      board62e.ini
; board id 5e65, "14", 10.71.71.146?? Not yet working
	      board62f.ini

[env:node32s]
platform = espressif32
framework = arduino
board = esp32dev # node32s
board_build.filesystem = littlefs
monitor_speed = 115200
check_tool = clangtidy
monitor_filters = esp32_exception_decoder
build_type = release
;lib_extra_dirs =
;	~/Projects2
lib_deps =
	og3@^0.4.2
	og3x-lora@^0.4.0
	og3x-satellite@^0.1.4
	og3x-shtc3@~0.3.0
	adafruit/Adafruit BusIO
	adafruit/Adafruit SHTC3 Library
	adafruit/Adafruit Unified Sensor
	bakercp/CRC32
	bblanchon/ArduinoJson@^7.0.0
	heman/AsyncMqttClient-esphome@^1.1.1
	nanopb/Nanopb
	ESP32Async/ESPAsyncWebServer @ 3.6.0
	sandeepmistry/LoRa@^0.8.0
	thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.2.0
	SPI

build_flags =
	'-Wall'
;	'-D LOG_DEBUG'
	'-D LOG_METHOD=App::LogType::k${log.logMethod}'
;	'-D LOG_METHOD=App::LogType::kNone'
	'-D LOG_UDP_ADDRESS=${secrets.udpLogTarget}'
	'-D OTA_PASSWORD="${secrets.otaPassword}"'
	'-D HARDWARE_VERSION_MAJOR=${board.boardMajorVersion}'
	'-D HARDWARE_VERSION_MINOR=${board.boardMinorVersion}'
;	'-DASYNC_TCP_SSL_ENABLED=1'
upload_protocol = ${secrets.uploadProtocol}
upload_port = ${secrets.uploadPort}
upload_flags =
	${secrets.uploadAuth}
	${secrets.uploadHostPort}
lib_ldf_mode = chain
lib_compat_mode = strict
